### ISSUE TITLE
TERRA-62 ⁃ Fix docs on Terraform 

### ISSUE THREAD

**Issue by melienherrera** [datastax/terraform-provider-astra#123]
On Terraform docs, resources` astra_streaming_stink` and `astra_streaming_tenant `have the same description as `astra_cdc`

See below for reference:
![docs1](https://user-images.githubusercontent.com/85907755/171498000-030ea7f2-5148-4c14-8c78-811b5a206d33.png)
![docs2](https://user-images.githubusercontent.com/85907755/171498010-78dcee7c-9859-4dd2-b527-8f3e356c8ae6.png)

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-62) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-62
┆priority: Major

**Comment by emerkle826** [comment]
This was fixed in version 2.1.0-rc4
