### ISSUE TITLE
TERRA-67 ⁃ Feature: add support for enumerating roles via a data source astra_roles

### ISSUE THREAD

**Issue by muresan** [datastax/terraform-provider-astra#143]
Ideally this should be a part of `astra_role` to allow lookups using names (which does not seem to be supported by the API) but a new data source that maps to the API also helps.

### Expected Behavior
Add support for `astra_roles`

### References
There is support in the DevOps API for this https://docs.datastax.com/en/astra/docs/_attachments/devopsv2.html#tag/Roles/operation/getOrganizationRoles

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-67) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-67
┆priority: Major

**Comment by emerkle826** [comment]
@muresan We should be able to implement this similar to how we have `astra_databases` implemented. Would something like that work for you?

**Comment by muresan** [comment]
Yes, like I mentioned in the References, mapping the API call is enough.
