### ISSUE TITLE
TERRA-71 ⁃ private_link reference for datacenter_id isn't working with aws 

### ISSUE THREAD

**Issue by bigjew92** [datastax/terraform-provider-astra#151]
I have another implementation that maybe works better. With it, you could reference the datacenter id like this:

```yaml
resource "astra_database" "terra59" {
  name           = "terra59"
  keyspace       = "terra59"
  cloud_provider = "gcp"
  regions        = ["us-east4"]
}

resource "astra_private_link" "example" {
  allowed_principals = ["some-principal"]
  database_id = astra_database.terra59.id
  datacenter_id = astra_database.terra59.datacenters["${astra_database.terra59.cloud_provider}.${astra_database.terra59.regions[0]}"]
}
```

where you would only have to make sure you use the right regions index.

The state file would look like this instead:

```yaml
resource "astra_database" "terra59" {
    additional_keyspaces = []
    cloud_provider       = "GCP"

    ...

    datacenters          = {
        "GCP.us-east4" = "26592405-0856-41cd-90ec-c25d039f4c13-1"
    }


    ...

    id                   = "26592405-0856-41cd-90ec-c25d039f4c13"

    ...
    regions              = [
        "us-east4",
    ]

    ...
```

_Originally posted by emerkle826 in https://github.com/datastax/terraform-provider-astra/issues/99#issuecomment-1159255706_

I tried to implement this for my resources, but I am using AWS. When using a similar set up to what is mentioned here, I get the following error

```bash
  on astra.tf line 47, in resource "astra_private_link" "example":
  47:   datacenter_id      = module.astra_db.datacenters["${module.astra_db.cloud_provider}.${module.astra_db.regions[0]}"]
    |----------------
    | module.astra_db.cloud_provider is "AWS"
    | module.astra_db.datacenters is map of string with 1 element
    | module.astra_db.regions[0] is "us-east-1"
```

This is my definition

```yaml
resource "astra_private_link" "example" {
  allowed_principals = ["arn:aws:iam::myaccountuser"]
  database_id        = module.astra_db.database_id
  datacenter_id      = module.astra_db.datacenters["${module.astra_db.cloud_provider}.${module.astra_db.regions[0]}"]
}
```

I tried to replace "${module.astra_db.cloud_provider}" with just "AWS" and it gave me a similar error.

```bash
Error: Invalid index

  on astra.tf line 47, in resource "astra_private_link" "example":
  47:   datacenter_id      = module.astra_db.datacenters["AWS.${module.astra_db.regions[0]}"]
    |----------------
    | module.astra_db.datacenters is map of string with 1 element
    | module.astra_db.regions[0] is "us-east-1"

The given key does not identify an element in this collection value.
```

When I replaced "${module.astra_db.cloud_provider}" with "aws", it successfully grabbed the datacenter_id I was looking for. 

It seems like the case of the cloud_provider is the issue.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-71) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-71
┆priority: Major

**Comment by emerkle826** [comment]
This should be fixed in v2.1.2 shortly. The safest fix was to just leave the cloud_provider and region casing alone, as changing the case for either/both to all UPPER or all lower could cause referencing issues in other places. Also, there's no guarantees that the regions will always be all lower, and that cloud providers will always be all upper. So whatever the DevOps API returns is what will be stored in the TF state and used for building the datacenter index key.

**Comment by emerkle826** [comment]
@bigjew92 I'll take a look.

**Comment by emerkle826** [comment]
@bigjew92 Import should work. Can you post the results of `terraform show` and redact your actual DB IDs? In particular, I'm curious as to what your datacenters look like in your TF state. Example:
```
    datacenters          = {
        "AWS.us-east-1" = "<uuid redacted>"
    }
```

Also, when you updated to v2.1.2, did you do the following:
```terraform init --upgrade```
and then
```terraform apply --refresh-only```

You may need to do the refresh to update the state so that the datacenters are saved correctly with the changes from 2.1.2.

If you did al that and still have the issue, let me know

**Comment by bigjew92** [comment]
@emerkle826 Apologies, needed the refresh, that seemed to work. Thank you. 

For the import, is the syntax the following:

```bash
terraform import 'module.privatelink.astra_private_link.private_link'**DB-ID**/datacenter/**DC-ID**/serviceNames/**SERVICE-NAME**
```
The docs for import seem to suggest instead of DC-ID, it's the DB-ID again, but that didn't make much sense, so I am assuming it's the above.

After importing and running another plan, it's showing a force of replacement. I also don't see the allowed_principles in the state, which is what I think is forcing the replacement.

```bash
  # module.privatelink.astra_private_link.private_link must be replaced
-/+ resource "astra_private_link" "private_link" {
      + allowed_principals = [
          + "arn:aws:iam::myaccountuser",
        ] # forces replacement
      ~ id                 = "DB-ID/datacenter/DC-ID/serviceNames/service_name" -> (known after apply)
      ~ service_name       = "service_name" -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```

```bash
> terraform state show module.privatelink.astra_private_link.private_link                                        
# module.privatelink.astra_private_link.private_link:
resource "astra_private_link" "private_link" {
    database_id   = "DB-ID"
    datacenter_id = "DC-ID"
    id            = "DB-ID"/datacenter/DC-ID"/serviceNames/service_name"
    service_name  = "service_name"
}
```

**Comment by emerkle826** [comment]
@bigjew92 I see the problem. The `allowed_principal` isn't getting written to state when the resource is imported. I'll get this fixed today.

**Comment by emerkle826** [comment]
This one should be resolved with v2.1.3 that will be released in a few minutes.

**Comment by bigjew92** [comment]
Looking much better. Thank you for such fast support @emerkle826!

**Comment by bigjew92** [comment]
@emerkle826 can open up another issue, but more so just looking for clarification on importing a private_link_endpoint. Docs aren't super clear as to what it's looking for. https://registry.terraform.io/providers/datastax/astra/latest/docs/resources/private_link_endpoint#import

Seems like it's asking for the database ID only?

**Comment by emerkle826** [comment]
Opened https://github.com/datastax/terraform-provider-astra/issues/155 to address the private link endpoint issue.
