### ISSUE TITLE
TERRA-76 ⁃ Question - Multi-region database creation times out within 20 minutes

### ISSUE THREAD

**Issue by giannoul** [datastax/terraform-provider-astra#163]
Hi there,

Please provide the following details with your issue report.

### Terraform Version
```
Terraform v1.1.8
on linux_amd64
```

### Affected Resource(s)
* astra_database

### Terraform Configuration Files
```hcl
resource "astra_database" "current" {
  name           = "test"
  keyspace       = "test"
  cloud_provider = "gcp"
  regions        = ["us-central1", "us-east4", "us-west4"]
}
```

### Debug Output
None

### Panic Output
None

### Expected Behavior
Create multi-region database

### Actual Behavior
Timeout in 20 minutes

### Steps to Reproduce
`terraform apply`

### Important Factoids
None

### References
None

As per the docs [here](https://github.com/datastax/terraform-provider-astra/blob/main/docs/resources/database.md#nested-schema-for-timeouts) there should be a configurable timeout, however the code [here](https://github.com/datastax/terraform-provider-astra/blob/main/internal/provider/resource_database.go#L24-L25) has the timeouts hardcoded. Can I set a timeout using what the docs say?

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-76) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-76
┆priority: Major

**Comment by emerkle826** [comment]
@giannoul The default timeout is 20 minutes, but you can override that in your Terraform resource definition. For example, you can add the `timeouts` block to the database definition and increase the create timeout to 45 minutes like this:
```cdl
resource "astra_database" "current" {
  name           = "test"
  keyspace       = "test"
  cloud_provider = "gcp"
  regions        = ["us-central1", "us-east4", "us-west4"]
  timeouts {
    create = "45m"
  }
}
```
There is a little bit more on the Terraform documentation page here:
https://www.terraform.io/plugin/sdkv2/resources/retries-and-customizable-timeouts#resources-retries-and-customizable-timeouts

A little more on the implementation of the provider. It uses the Astra DevOps API under the hood. The API only supports adding 1 region at a time. To deploy a database into more than 2 regions, the provider first creates the database, then makes the API call to add a region one at a time. It seems that adding a region can take up to 15 minutes per region after you have 2, so you can use that as a rough guide for how long you should extend the timeout, depending on how many additional regions you want to deploy to.

With the above terraform definition, I was able to deploy the database into all 3 regions in about 25 minutes, so I probably could have gotten away with a shorter timeout.
