### ISSUE TITLE
TERRA-77 ⁃ Table creation sporadically fails

### ISSUE THREAD

**Issue by emerkle826** [datastax/terraform-provider-astra#164]
### Affected Resource(s)
Please list the resources as a list, for example:

* astra_table

### Terraform Configuration Files
```hcl
resource "astra_keyspace" "puppies" {
 ...
}

resource "astra_table" "table" {
 table   = "mytable"
 keyspace  = "puppies"
 depends_on = astra_keyspace.puppies
}
```

### Expected Behavior
Provider should ensure the keyspace exists before attempting to create a table.

### Actual Behavior
Sporadically, table creation will fail with `keyspace does not exist`

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-77) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-77
┆priority: Major

**Comment by emerkle826** [comment]
Closing this as it seems adding
```
depends_on = [astra_keyspace.puppies]
```
might solve the issue

**Comment by alkeshdatastax** [comment]
Thanks Erik, you are correct. Adding **depends_on** helps to add an explicit dependency to ensure table creation doesn't run until keyspace already exists.  This helps to resolve the issue.
