### ISSUE TITLE
TERRA-87 ⁃ Manage tokens for Astra Streaming

### ISSUE THREAD

**Issue by oscar-b** [datastax/terraform-provider-astra#180]
It would be very nice to be able to manage tokens for Astra Streaming so that they can be automatically deployed.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-87) by [Unito](https://www.unito.io)
┆Issue Number: TERRA-87
┆Priority: Major
┆Link To Issue: https://datastax-oss.atlassian.net/browse/TERRA-87

**Comment by emerkle826** [comment]
@oscar-b I have a PR up that should add the missing URLs to the resource object. I've also added the Pulsar JWT token that is returned when creating a tenant. Is that sufficient for your needs, or did you need more/something else? For example, if you crate a tenant now, the terraform resource state should look something like this (with `terraform show` after applying):
```yaml
resource "astra_streaming_tenant" "tenant" {
    broker_service_url         = "pulsar+ssl://pulsar-gcp-useast4.streaming.datastax.com:6651"
    cloud_provider             = "gcp"
    id                         = "tenant1"
    pulsar_token               = (sensitive value)
    region                     = "us-east4"
    tenant_name                = "tenant1"
    topic                      = "topic1"
    user_email                 = "erik.merkle@datastax.com"
    web_service_url            = "https://pulsar-gcp-useast4.api.streaming.datastax.com"
    web_socket_query_param_url = "wss://pulsar-gcp-useast4.streaming.datastax.com:8964/ws/v2"
    web_socket_url             = "wss://pulsar-gcp-useast4.streaming.datastax.com:8001/ws/v2"
}
```

While the state will show the token as `(sensitive value)`, the state file will have the token that was returned and it should be able to be referenced from other terraform resources.
