### ISSUE TITLE
TERRA-90 ⁃ Handle Token updates for astra_streaming_tenant

### ISSUE THREAD

**Issue by emerkle826** [datastax/terraform-provider-astra#188]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- astra_streaming_tenant

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "astra_database" "db" {
  name           = "db"
  keyspace       = "testks"
  cloud_provider = "gcp"
  regions        = ["us-east4"]
}

resource "astra_streaming_tenant" "tenant" {
  tenant_name        = "tenant1"
  topic              = "topic1"
  region             = "us-east4"
  cloud_provider     = "gcp"
  user_email         = "user@example.com"
}
```

### Debug Output
```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # module.test-project.module.astra-streaming.astra_streaming_tenant.main has changed
  ~ resource "astra_streaming_tenant" "tenant" {
        id                         = "aaa-test-43472"
      ~ pulsar_token               = (sensitive value)
        # (10 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.
```

### Expected Behavior
Terraform should not detect the resource as being changed when no changes are made to the resource.

### Actual Behavior
Terraform detects the streaming tenant resource as modified every time `terraform apply` is called, even when no changes are made. This is because the underlying DevOps API call to get the tenant information returns a response with an updated JWT token.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply --refresh-only`

### Important Factoids
N/A

### References
#185

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-90) by [Unito](https://www.unito.io)
┆Issue Number: TERRA-90
┆Priority: Major

**Comment by emerkle826** [comment]
@oscar-b Tagging you here as it's a new ticket and I want to leave the merged PR comments alone.

What I'm seeing is that if I create a tenant with `terraform apply`, it creates it fine and sets the JWT/Pulsar token. If I follow up with a `terraform apply` again, it doesn't ask me to accept changes. However, if I enable logs, I do see this:

```
TF_LOG=WARN terraform apply
2022-11-15T14:46:28.228-0600 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/datastax/astra\"]" changed the config value, but that value is unused
astra_streaming_tenant.tenant: Refreshing state... [id=tenant1]
astra_database.terra-90: Refreshing state... [id=91fc8515-a74b-4441-9537-cea39a189147]
2022-11-15T14:46:28.707-0600 [WARN]  Provider "registry.terraform.io/datastax/astra" produced an unexpected new value for astra_streaming_tenant.tenant during refresh.
      - .pulsar_token: inconsistent values for sensitive attribute

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
It detects the change in the token, but it seems to just apply the change to my state. So if I look at my local `terraform.tfstate` file, I can see that the token changes between the 2 calls to `terrafrom apply`

Now, if I use `terrafrom apply --refresh-only`, I do get prompted:
```
TF_LOG=WARN terraform apply --refresh-only
2022-11-15T14:49:16.589-0600 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/datastax/astra\"]" changed the config value, but that value is unused
astra_streaming_tenant.tenant: Refreshing state... [id=tenant1]
astra_database.terra-90: Refreshing state... [id=91fc8515-a74b-4441-9537-cea39a189147]
2022-11-15T14:49:17.057-0600 [WARN]  Provider "registry.terraform.io/datastax/astra" produced an unexpected new value for astra_streaming_tenant.tenant during refresh.
      - .pulsar_token: inconsistent values for sensitive attribute

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # astra_streaming_tenant.tenant has changed
  ~ resource "astra_streaming_tenant" "tenant" {
        id                         = "tenant1"
      ~ pulsar_token               = (sensitive value)
        # (10 unchanged attributes hidden)
    }
```

Do you get prompted on `terraform apply`? Or just when you try to refresh the state with `terraform apply --refresh-only`?

**Comment by oscar-b** [comment]
@emerkle826 Not sure if it's related to the fact that you don't actually use the value anywhere? I do see the behavior in regular `terraform apply`. I save the value in a GCP Secret.

**Comment by oscar-b** [comment]
```
terraform -v
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/datastax/astra v2.1.8
+ provider registry.terraform.io/elastic/ec v0.5.0
+ provider registry.terraform.io/elastic/elasticstack v0.4.0
+ provider registry.terraform.io/hashicorp/google v4.43.0
+ provider registry.terraform.io/hashicorp/google-beta v4.43.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

**Comment by emerkle826** [comment]
> @emerkle826 Not sure if it's related to the fact that you don't actually use the value anywhere? I do see the behavior in regular `terraform apply`. I save the value in a GCP Secret.

That might be the difference. Thanks for the update.

Out of curiosity, do you know if the older generated tokens are invalidated for your use? Or are they still valid after terraform gets a new token?

**Comment by oscar-b** [comment]
> Out of curiosity, do you know if the older generated tokens are invalidated for your use? Or are they still valid after terraform gets a new token?

Haven't been able to test it yet, was planning on doing that tomorrow :)

**Comment by emerkle826** [comment]
@oscar-b I have a PR up now for this. It will change how you handle the token for a streaming tenant.

For now, there isn't a way to create tokens via the DevOps API, so I've removed the token from the `astra_streaming-tenant` resource and created a separate `astra_streaming-tenant_tokens` datasource (see the example [here](https://github.com/datastax/terraform-provider-astra/pull/189/files#diff-41e10cecc5f36e295f441726d503ca20e793c11f4859da089691fdbc544858ebR16-R34))

This should allow you to define a tenant resource, and then a tokens datasource that references the tenant resource. The datasource will then have a list of tokens (only one in the list for the tenant unless you add more via the UI) that you should be able to refer to in other terrafrom datasources/resources. Example:

```hcl
resource "astra_streaming_tenant" "tenant" {
  tenant_name        = "tenantexample"
  topic              = "topic1"
  region             = "us-east4"
  cloud_provider     = "gcp"
  user_email         = "user@example.com"
}

data "astra_streaming_tenant_tokens" "tokenlist" {
  tenant_name  = astra_streaming_tenant.tenant.tenant_name
  cluster_name = astra_streaming_tenant.tenant.cluster_name
}

resource "foo" "bar" {
  token = data.astra_streaming_tenant_tokens.tokenlist.tokens[0].token
}
```

Doing this should allow for you to reference the token that is created when you create the tenant without terraform detecting a change in the token every time you do a `terraform apply`. Also, if you do a `terraform apply --refresh-only`, the tokens will be updated, as they will be re-fetched, but the provider won't prompt you to accept a config change, since it is simply a datasource.

At some point, the DevOps API may include token create/delet operations, at which time I can add them to the provider.

**Comment by oscar-b** [comment]
@emerkle826 Sorry I haven't been able to test this until now.

I got this warning when using the new modules:

```
-/+ resource "google_secret_manager_secret_version" "main" {
      ~ create_time  = "2022-11-16T12:57:40.465164Z" -> (known after apply)
      ~ destroy_time = "" -> (known after apply)
      ~ id           = "projects/..." -> (known after apply)
      ~ name         = "projects/..." -> (known after apply)
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change.
      ~ secret_data  = (sensitive value) # forces replacement
      ~ version      = "5" -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```

Not sure if `secret_data` in `google_secret_manager_secret_version` is marked sensitive either way, so it doesn't matter?

**Comment by oscar-b** [comment]
@emerkle826 Using `astra_streaming_tenant_tokens` still forces a replacement on each apply.

```
-/+ resource "google_secret_manager_secret_version" "main" {
      ~ create_time  = "2022-11-28T11:09:11.367482Z" -> (known after apply)
      + destroy_time = (known after apply)
      ~ id           = "projects/.../versions/12" -> (known after apply)
      ~ name         = "projects/.../versions/12" -> (known after apply)
      ~ secret_data  = (sensitive value) # forces replacement
      ~ version      = "12" -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```

**Comment by oscar-b** [comment]
Using this TF code:


```
data "astra_streaming_tenant_tokens" "main" {
  tenant_name  = astra_streaming_tenant.main.tenant_name
  cluster_name = astra_streaming_tenant.main.cluster_name
}

resource "google_secret_manager_secret" "main" {
  secret_id = "astra-streaming-${var.project_id}-token"
  labels    = local.labels

  replication {
    automatic = true
  }

  depends_on = [google_project_service.secretmanager-api]
}

resource "google_secret_manager_secret_iam_member" "main" {
  secret_id = google_secret_manager_secret.main.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${var.service_account_email}"
}

resource "google_secret_manager_secret_version" "main" {
  secret      = google_secret_manager_secret.main.id
  secret_data = data.astra_streaming_tenant_tokens.main.tokens[0].token
}

```

**Comment by emerkle826** [comment]
@oscar-b thanks for testing it, I'm going to capture your latest comments into a new ticket.
