### ISSUE TITLE
TERRA-94 ⁃ Add `deletion_protection` to Astra DB and Astra Streaming

### ISSUE THREAD

**Issue by oscar-b** [datastax/terraform-provider-astra#194]
It would be nice if the provider protected Astra DB and Astra Streaming from deletion, like Google does for Cloud SQL: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection

Basically you have a variable that defaults to `true`, which you need to explicitly set to `false` in order to delete the database.

This would make it a lot harder to delete stuff by mistake :)

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-94) by [Unito](https://www.unito.io)
┆Issue Number: TERRA-94
┆Priority: Major

**Comment by emerkle826** [comment]
Thanks for the suggestion. I'll try to get this in soon.

**Comment by emerkle826** [comment]
@oscar-b which Streaming resources did you want this for?
- astra_streaming_tenant
- astra_streaming_sink
- astra_streaming_topic

All of them?

**Comment by oscar-b** [comment]
@emerkle826 Anything that could mean data loss, I guess?

**Comment by emerkle826** [comment]
Just released in v2.1.14
