### ISSUE TITLE
TERRA-100 ⁃ Importing `astra_streaming_tenant` doesn't work

### ISSUE THREAD

**Issue by oscar-b** [datastax/terraform-provider-astra#210]
Hi there,

Please provide the following details with your issue report.

### Terraform Version
```
terraform -v
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/datastax/astra v2.1.14
+ provider registry.terraform.io/elastic/ec v0.5.0
+ provider registry.terraform.io/elastic/elasticstack v0.4.0
+ provider registry.terraform.io/hashicorp/google v4.44.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Affected Resource(s)
Please list the resources as a list, for example:
- astra_streaming_tenant

### Expected Behavior
Import should import to the state properly

### Actual Behavior
Import succeeds, but is missing properties so that the next apply tries to destroy the resource

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import module.infrastructure.module.astra-streaming.astra_streaming_tenant.main tenant_name`
2. `terraform state show module.infrastructure.module.astra-streaming.astra_streaming_tenant.main`
3. `terraform apply`

Notice how missing parameters `cloud_provider`, `region`, `topic` and `user_email` triggers the resource to be replaced.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-100) by [Unito](https://www.unito.io)
┆Issue Number: TERRA-100
┆Priority: Major

**Comment by pgier** [comment]
This should be fixed in the next release (#232).  However, after import you will still see a diff of user_email, topic, and deletion_protection, but not of these require the resource to be replaced, and all three are a local state update only so no changes actually take place on the server.
