### ISSUE TITLE
Application token resource

### ISSUE THREAD

**Issue by FRosner** [datastax/terraform-provider-astra#22]
When connecting to the database using the document API, you need to provide an application token. Since application tokens can be managed using the [DevOps API](https://docs.datastax.com/en/astra/docs/db-devops-tokens.html) it should be possible to manage them as a Terraform resource as well.

The advantage is that they can be created automatically and passed to the application or a secrets store, which are also managed as Terraform resources.

**Comment by phact** [comment]
We need this functionality in devops api in order to expose in the provider.

**Comment by FRosner** [comment]
> We need this functionality in devops api in order to expose in the provider.

Isn't it supported? I was looking at https://docs.datastax.com/en/astra/docs/db-devops-tokens.html but I haven't tried it.

**Comment by phact** [comment]
This is done
