### ISSUE TITLE
TERRA-105 ⁃ Encountered error during tutorial.

### ISSUE THREAD

**Issue by boxcolli** [datastax/terraform-provider-astra#222]
Hi there,

### Terraform Version
```
Terraform v1.4.4
on windows_amd64
+ provider registry.terraform.io/datastax/astra v2.1.15
```

### Affected Resource(s)
- astra_database

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    astra = {
      source = "datastax/astra"
      version = ">= 2.1.0-rc1"
    }
  }
}

locals {
  astra_token = jsondecode(file("${path.module}/${var.astra_token_path}"))
}

provider "astra" {
  token = local.astra_token.token
}

resource "astra_database" "astra_pl" {
  name           = var.astra_database
  keyspace       = var.astra_database
  cloud_provider = var.astra_cloud_provider
  regions        = [var.astra_region]
}

resource "astra_keyspace" "astra_keyspace_chat" {
  name        = "chat"
  database_id = astra_database.astra_pl.id
}
```

### Debug Output
https://gist.github.com/boxcolli/1e803deac2515ab9bf17ba558e15c19f

### Panic Output
No panic

### Expected Behavior
A database with an keyspace should be created, and another keyspace should be created after.

### Actual Behavior
- Terraform threw an error (`unexpected response fetching database: null`) in about less than 5 seconds.
- From DS Astra console, a database with an keyspace is created as pending state.
- Additional keyspace didn't appeared.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I am using Free plan. 😥 And I'm roughly thinking that it caused long pending state or unexpected http response status.

### References
Nothing

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-105) by [Unito](https://www.unito.io)
┆Issue Number: TERRA-105
┆Priority: Major

**Comment by pgier** [comment]
It's not obvious from the logs where the problem is.  I'm guessing the variables like `var.astra_database` are defined in a variables.tf?   Are you able to reproduce this issue with the latest release (2.2.2)?
