### ISSUE TITLE
Unable to Create astra_role due to unknown error

### ISSUE THREAD

**Issue by theharrisonchow** [datastax/terraform-provider-astra#28]
Hi there,

Please provide the following details with your issue report.

### Terraform Version
```
tf -v
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/datastax/astra v1.0.3
```

### Affected Resource(s)
- astra_role

### Terraform Configuration Files
```hcl
resource "astra_role" "role" {
  role_name   = "name"
  description = "desc"
  effect      = "allow"
  resources = [
    "drn:astra:org:hiddenOrgId",
    "drn:astra:org:hiddenOrgId:db:hiddenDbId",
    "drn:astra:org:hiddenOrgId:db:hiddenDbId:keyspace:system_schema:table:*",
    "drn:astra:org:hiddenOrgId:db:hiddenDbId:keyspace:system:table:*",
    "drn:astra:org:hiddenOrgId:db:hiddenDbId:keyspace:system_virtual_schema:table:*",
    "drn:astra:org:hiddenOrgId:db:hiddenDbId:keyspace:*",
    "drn:astra:org:hiddenOrgId:db:hiddenDbId:keyspace:*:table:*"
  ]
  policy = ["accesslist-read", "db-all-keyspace-describe", "db-keyspace-describe", "db-table-select", "db-table-describe", "db-graphql", "db-rest", "db-cql"]
}
```

### Debug Output
```
╷
│ Error: json: cannot unmarshal string into Go value of type astra.Errors
│ 
│   with astra_role.role,
│   on main.tf line 32, in resource "astra_role" "role":
│   32: resource "astra_role" "role" {
│ 
╵

```

### Expected Behavior
Role should be created

### Actual Behavior
Unknown Error

### Important Factoids
POST request based on the following guide works: https://docs.datastax.com/en/astra/docs/db-devops-roles.html#_create_a_new_role

Exact same request made on curl works, but not via tf provider.

**Comment by phact** [comment]
Thanks for the report!

There are a few places in the provider right now where we're swallowing exceptions like this. We'll fix it, stay tuned.

**Comment by phact** [comment]
Just pushed v1.0.8 with the fix for this bug

**Comment by ivnovi** [comment]
In my case I had same error but finally figured that it was due to missing permissions. API Admin wasn't enough to manage roles. But message is similarly non-descriptive in newer 1.0.8 and 1.0.9 versions and probably should be improved.

**Comment by phact** [comment]
@ivnovi could you open a fresh ticket for that?
This particular issue turned out to be a bug in the provider, not a swallowed exception like I first thought.
