### ISSUE TITLE
Unable to create datastax/astra database due to 'plugin did not respond'

### ISSUE THREAD

**Issue by Naveen-Kumar-G** [datastax/terraform-provider-astra#30]
Hi there,

Unable to create datastax/astra database due to 'plugin did not respond'.

### Affected Resource(s)
- astra_database
- astra_keyspace
- astra_roles
- astra_tokens

### Expected Behavior
datastax/astra provider should be able to connect to my astra db and acquire the state

### Actual Behavior
Plugin did not respond

```
│ Error: Plugin did not respond
│ 
│   with astra_database.myastra-db,
│   on main.tf line 1, in resource "astra_database" "myastra-db":
│    1: resource "astra_database" "myastra-db" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
```

### Steps to Reproduce
1. `terraform plan`

**Comment by phact** [comment]
Can you share your resources.tf and data-source.tf if you have one?

**Comment by Naveen-Kumar-G** [comment]
We have identified the root cause of the issue, it's causing due to Firewall communication to API, now added IP's to route table and the pipeline is running successfully without any issue

Failed at file: https://github.com/datastax/terraform-provider-astra/blob/main/internal/provider/provider.go
below section (line 83)

```
if resp.Request.Method == "POST" {
	return false, err
}
```

log screenshot:
![POST request](https://user-images.githubusercontent.com/89991718/132395445-bb9a33e8-8386-4f77-9382-d9399065b7f6.PNG)
