### ISSUE TITLE
Topic destruction fail with silent error

### ISSUE THREAD

**Issue by corentinFaucher** [datastax/terraform-provider-astra#338]
Hi,

With a `terraform destroy`, topic deletion with active subscriptions doesn't work correctly, the terraform state is updated and the command end successfully, but the topic is not deleted. No errors or warnings come up during deletion, but when I run a `terraform apply` again, I have an error because the topic already exists, since it hasn't been deleted correctly.

### Terraform Version
1.6.6 (latest)

### Affected Resource(s)
- astra_streaming_topic

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    astra = {
      source = "datastax/astra"
      version = "2.2.7"
    }
  }
}

provider "astra" {
  token = "<my-token>"
}

# Create a new topic
resource "astra_streaming_topic" "streaming_topic" {
  cluster   = "pulsar-aws-euwest1"
  tenant    = "my-tenant"
  namespace = "my-namespace"
  topic     = "test"

  deletion_protection = false
  num_partitions      = 1
  partitioned         = false
  persistent          = true

  lifecycle {
      ignore_changes = [
        schema
      ]
  }
}
```

### Debug Output
This is a [link](https://gist.github.com/corentinFaucher/61bd24bd99cecacca90d293ae765047a) with logs of the steps to reproduce the problem.

### Expected Behavior
The topic should be deleted or `terraform destroy` must at least raised an error without deleting `astra_streaming_topic` from terraform states.

### Actual Behavior
The `astra_streaming_topic` is not deleted even if `terraform destroy` end with success.

### Steps to Reproduce
1. `terraform apply`
2. Create a subscription on the topic via the interface of datastax for example.
![image](https://github.com/datastax/terraform-provider-astra/assets/109349274/d7db8368-7623-4229-ad51-000a688cf72b)
3.`terraform destroy`
4.`terraform apply`

Thanks in advance

**Comment by pgier** [comment]
Thanks, I was able to reproduce this, and it should be fixed by #346
