### ISSUE TITLE
Terraform import is failing for topic names containing a hyphen character.

### ISSUE THREAD

**Issue by awilsonv** [datastax/terraform-provider-astra#347]
### Terraform Version
`❯ terraform -v
Terraform v1.7.1
on darwin_arm64`

terraform import for an existing topic whose name contains a hyphen character:
`❯ terraform import astra_streaming_topic.streaming_topic pulsar-azure-westeurope:persistent://testawil/default/my-topic
astra_streaming_topic.streaming_topic: Importing from ID "pulsar-azure-westeurope:persistent://testawil/default/my-topic"...
astra_streaming_topic.streaming_topic: Import prepared!
  Prepared astra_streaming_topic for import
astra_streaming_topic.streaming_topic: Refreshing state...
╷
│ Error: failed to read topic
│
│ Received status code: '404', with content: {"reason":"Topic not found"}
╵`

The same command line works for a topic name without a hyphen character.

**Comment by pgier** [comment]
I wasn't able to reproduce this.  Is the topic that you are trying to import a partitioned topic?

**Comment by pgier** [comment]
I think this is a documentation issue.  I've added some details to the docs in #349
