### ISSUE TITLE
How to Deploy a Database in Multiple region

### ISSUE THREAD

**Issue by navjyotnishant** [datastax/terraform-provider-astra#35]
Hi There,

Please provide the following details with your issue report.

### Terraform Version
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/datastax/astra v1.0.9

### Affected Resource(s)
Please list the resources as a list, for example:

* astra_database

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "astra_database" "Test"{
  name           = "terra-test-cluster"
  keyspace       = "terraformTest"
  cloud_provider = "aws"
  region         = ["us-east-1","us-west-2"]
}

```

### Debug Output
terraform plan
╷
│ Error: Incorrect attribute value type
│
│   on casdev.tf line 19, in resource "astra_database" "Test":
│   19:   region         = ["us-east-1","us-west-2"]
│
│ Inappropriate value for attribute "region": string required.

### Expected Behavior
It should deploy database in multiple region.

### Actual Behavior
Deployment in only 1 region supported. Also there are no resource to add new regions.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-34) by [Unito](https://www.unito.io)

**Comment by jdonenine** [comment]
### Notes

* Within the devops API the /v2/databases endpoint https://docs.datastax.com/en/astra/docs/_attachments/devopsv2.html#operation/createDatabase regions is a string, not an object or an array where mulitple could be added
* we need to confirm the current state of that endpoint and if there is an endpoint (either newer version or whatever) that supports multiple regions

**Comment by navjyotnishant** [comment]
@jdonenine 

> At the moment, there is no timeline for the feature, our current focus has been on cleaning up a few bugs. We'll be considering new features soon. If it's something that you might be interested in working on and contributing to the project we'd love to have some additional contributors!

Would Love to contribute if that can speedup the new feature implementation. Let me know how I can help!

**Comment by jdonenine** [comment]
Ah, thanks for the link @navjyotnishant, we hadn't yet really looked into it too much, and this it looks like is the answer we needed.

Generally speaking, we'd love to collaborate on the enhancement if you're interested!  Perhaps all of us (@emerkle826 @jeffbanks ) could discuss a proposal for how to represent this within the terraform side of things?

If you have a proposal @navjyotnishant that would be a great start.  I know @emerkle826 has thought about this a little bit, but not sure how far down that path he is at this point?

Thanks!

**Comment by emerkle826** [comment]
I haven't dug into this one much yet, so feel free to put something together. Will be glad to help push it along.

**Comment by jdonenine** [comment]
@navjyotnishant we've shifted around some priorities and we're going to start looking at this multi-region support this week, but if you've already put any thought into the structure of the resources to be used please feel free to share them with @emerkle826 as he gets going on things here.
