### ISSUE TITLE
astra_streaming_namespace does not manage "Subscription Expiration Time" setting

### ISSUE THREAD

**Issue by ojcm** [datastax/terraform-provider-astra#356]
### Terraform Version
Provider version 2.2.8

### Affected Resource(s)
- astra_streaming_namespace

### Expected Behavior
`astra_streaming_namespace` schema should include an option to set the "Subscription Expiration Time" and TF should manage this field.

### Actual Behavior
No option available to set this field and manual changes to that field (e.g. via UI) are not detected by TF.

### Steps to Reproduce
1. Terraform a namespace
2. Manually change "Subscription Expiration Time"
3. Run `tf plan` and see that the change hasn't been detected.

**Comment by pgier** [comment]
Fixed in #373
