### ISSUE TITLE
How to Deploy a User in Astra?

### ISSUE THREAD

**Issue by navjyotnishant** [datastax/terraform-provider-astra#36]
Hi There,

Please provide the following details with your issue report.

### Terraform Version
Terraform v1.0.7
on linux_amd64

* provider registry.terraform.io/datastax/astra v1.0.9

### Affected Resource(s)
Please list the resources as a list, for example:

* NA
* 
* Resource doesn't exists.

If this issue appears to affect multiple resources, it may be an issue with Terraforms core, so please mention this.

Resource doesn't exists. 

```

### Debug Output
NA

### Expected Behavior
Need functionality to deploy User. 

### Actual Behavior
Create_user resource doesn't exists.



┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-35) by [Unito](https://www.unito.io)

**Comment by jdonenine** [comment]
### Notes

* We currently do not have a function to create an invite for a user as is described in the issue
* We need to think about if there is a good reason this doesn't exist
* Inviting a user is available in Astra as is a function to revoke the users invitation
* But this is an invitation, not the direct creation of a user so to speak
* What would it mean if the user invitation was removed from the plan an re-applied, should we revoke the invitation at that point?

**Comment by ivnovi** [comment]
I suppose this should be pretty straight-forward, user either exists in org and has provided role or not, depending whether it exists in plan. Similar as tokens, even if users are not really created, main thing whether they have access within current org or not.

I also noticed that when you update role permissions it gets recreated and any use had this role has to be manually added again, which is not optimal, but wouldn't be problem if user relation to role was also in code.

**Comment by emerkle826** [comment]
Please reopen this issue if there is still a need
