### ISSUE TITLE
Cannot attach default role to token generated by Terraform

### ISSUE THREAD

**Issue by useownyxis** [datastax/terraform-provider-astra#40]
Hi,
I tried to use default roles with token generated by Terraform. As I see in terraform documentation, I may do that. ("Custom roles can be assigned to an Astra user is to grant them granular permissions when the default roles in the UI are not specific enough."). 
https://registry.terraform.io/providers/datastax/astra/latest/docs/resources/role
But nothing happens when I applied it. In UI I see "N/A" role. I also tried to use custom role, which I define by using UI.

Terraform v0.15.4
on darwin_amd64

* provider registry.terraform.io/datastax/astra v1.0.9

### Affected Resource(s)
* astra_token

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    astra = {
      source = "datastax/astra"
      version = ">= 1.0.7"
    }
  }
}

provider "astra" {}

resource "astra_token" "cassandra_admin" {
  roles = ["Administrator User"]
}
```

### Expected Behavior
Default role such as "Administrator User", "Admin User", "Organization Administrator" should attach to token.

### Actual Behavior
Role doesn’t attach to token, in UI I see "N/A"

### Steps to Reproduce
1. Copy Terraform code
1. `terraform apply`
1. Go to UI and check role that attached to token

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-37) by [Unito](https://www.unito.io)

**Comment by jdonenine** [comment]
### Notes

* Confirmed that when building a token through the UI the default "Administrator User" role does populate the table with the "Admin Role" name as described being expected

![image](https://user-images.githubusercontent.com/7901615/139483738-b4245b56-09c3-4479-8ebe-bf3ebc060777.png)

* We need to test what happens when doing this via Terraform

**Comment by emerkle826** [comment]
The issue is with the configuration file. You are specifying `"Administrator User"` as the value for `role`, but it needs to be the `id`, not the name of the role. Find the ID for the role(s) you want to use and use the ID(s):
```yaml
terraform {
  required_providers {
    astra = {
      source = "datastax/astra"
      version = ">= 1.0.7"
    }
  }
}

provider "astra" {}

resource "astra_token" "cassandra_admin" {
  roles = ["43745b73-ad46-46e4-b826-c15d06d2cea0"]
}
```
