### ISSUE TITLE
Tests should not rely on hard-coded resource identifiers

### ISSUE THREAD

**Issue by jdonenine** [datastax/terraform-provider-astra#42]
Currently a number of our tests rely on hard-coded resource IDs, either within Astra or another provider.  These should be removed in favor of automatically generated resources that are created at startup and cleaned up at test completion.  Any unique content, such as user account information for the cloud providers should be extracted to secrets that can be provided via environment variables.

This was mentioned during initial project transition meetings and again in the review of #41 .

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-38) by [Unito](https://www.unito.io)

**Comment by jdonenine** [comment]
@emerkle826 is going to think through some of the enhancements we'd need/like to see in the testing framework as a whole to make supporting changes to the test like this more manageable.  When that design is completed we'll revisit what to explicitly do with this issue here.  It may get expanded and split out into more specific issues or consumed by other issues.

**Comment by jeffbanks** [comment]
@jdonenine and @emerkle826 do we have any thoughts around breaking this out into sub-tickets?  I have a few starters that might get the ball rolling for our tests based on some recent research of TF.

* Setup and teardown capabilities for Astra instances in integration and e2e tests
* Handling of Astra sensitive test inputs & decoupling of test inputs
* Ensure unit and integration test separation
* Include tests with GCP and Azure cloud
* Provide parallel integration test execution where applicable

**Comment by jdonenine** [comment]
That's a great idea @jeffbanks what we had here before was more placeholder than anything.

**Comment by pgier** [comment]
Closing this because most of it has been addressed by #231 
We can create new issues for further improvements to the CI
