### ISSUE TITLE
TERRA-44 ⁃ Not all database attributes are available

### ISSUE THREAD

**Issue by jdavies** [datastax/terraform-provider-astra#52]
Hi all,
   When I create a database, I output some of the database attributes at the end. I'm using the attributes listed on the database resource page. Many of the attributes print just fine, but the following output statements produce no output at all avd no error messages:

```hcl
### These commands are not displayed after the "apply"
output "replication_factor" {
  value = astra_database.hello_astra_db.replication_factor
  description = "Replicaion Factor"
}

output "node_count" {
  value = astra_database.hello_astra_db.node_count
  description = "Node Count"
}

output "total_storage" {
  value = astra_database.hello_astra_db.total_storage
  description = "Total Storage (GB?)"
}
```

### Terraform Version
jeffdavies@jdavies-rmbp16 hello_astra_tf % terraform -v
Terraform v1.0.11
on darwin_amd64

### Affected Resource(s)
* astra_database

### Terraform Configuration Files
I have attached a ZIP file with my terraform files. But really, just create an Astra database and use my code snippet above and you will see that no output or error message is produced.

### Debug Output
None

### Panic Output
None

### Expected Behavior
I expect to see the values displayed on my console with the other values.

### Actual Behavior
no output for the listed values.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
None

### References
None

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-44) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-44
┆priority: Major

**Comment by jdavies** [comment]
[test.zip](https://github.com/datastax/terraform-provider-astra/files/7582885/test.zip)

**Comment by emerkle826** [comment]
Sorry it took a bit to get around to this. I see the problem and it should be an easy fix. The 3 fields you mention are skipped in the [flattenDatabase](https://github.com/datastax/terraform-provider-astra/blob/main/internal/provider/resource_database.go#L355-L378) function that maps the Astra database response to a terraform resource struct. Should be as simple as adding the correct mapping for them in that function.
I can get to this as soon as I get Multi-region support merged.
