### ISSUE TITLE
TERRA-47 ⁃ Terraform plan fails for previously created database

### ISSUE THREAD

**Issue by edmeister** [datastax/terraform-provider-astra#57]
Hi there,

Please provide the following details with your issue report.

### Terraform Version
Latest
Plugin 1.0.13

### Affected Resource(s)
Please list the resources as a list, for example:

* astra_database

### Actual Behavior
During a terraform plan of an environment that previously had a database created, we now encounter the following error:

```
12:19:26  ╷
12:19:26  │ Error: error fetching database: {"errors":[{"ID":340012,"message":"invalid token format"}]}
12:19:26  │ 
12:19:26  │ 
12:19:26  ╵
12:19:26  ╷
12:19:26  │ Error: unexpected response fetching database (*****REDACTED*****): {"errors":[{"ID":340012,"message":"invalid token format"}]}
12:19:26  │ 
12:19:26  │   with module.astra.astra_database.database,
12:19:26  │   on .terraform/modules/astra/terraform/main.tf line 5, in resource "astra_database" "database":
12:19:26  │    5: resource "astra_database" "database" {
12:19:26  │ 
12:19:26  ╵
```

Any idea what might be going wrong? I will try debug logging asap.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-47) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-47
┆priority: Major

**Comment by edmeister** [comment]
The token wasn't added to the environment variables. Very stupid.

**Comment by emerkle826** [comment]
I was going to suggest that your token was missing or maybe a typo when supplying it. Glad you got it fixed.
