### ISSUE TITLE
TERRA-53 ⁃ Documentation: astra_database, needs more details on required attributes 

### ISSUE THREAD

**Issue by tringuyen-yw** [datastax/terraform-provider-astra#79]
### Terraform Version
Terraform v1.1.5
on linux_amd64

### Affected Resource(s)
- astra_database

The official TF doc: https://registry.terraform.io/providers/datastax/astra/latest/docs/resources/database needs more guidance on the description and usage of the required attributes. Example:

- `cloud_provider`: what are the list of valid values? 
- `keyspace`: Why does this DB needs that exact keyspace?
- `regions`: list of valid values? Would be helpful to give an example of CLI query to get the list of valid values. For example, if the Cloud provider is Azure. Maybe the list of valid regions could be `az account list-locations --query "[?@.metadata.geographyGroup=='Canada'].{ displayName: displayName, name: name}"`

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-53) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-53
┆priority: Major

**Comment by emerkle826** [comment]
I won't close this issue until I am able to update the docs to reflect these clarification, but I wanted to at least reply with some quick answers to your questions for now:

> * `cloud_provider`: what are the list of valid values?

The supported cloud providers are `aws`, `gcp` and `azure`

> * `keyspace`: Why does this DB needs that exact keyspace?

When creating an Astra Database, you must create an initial keyspace. The keyspace name can be any valid Astra Database keysapce name (see https://docs.datastax.com/en/astra/docs/creating-your-astra-database.html)

> * `regions`: list of valid values? Would be helpful to give an example of CLI query to get the list of valid values. 

The list of values depends on the cloud provider you choose and which regions are available in Astra for that provider (see https://docs.datastax.com/en/astra/docs/database-regions.html).

**Comment by tringuyen-yw** [comment]
Thanks @emerkle826 for the detailed answer. Can you please make sure the Terraform documentation pages contains the links to https://docs.datastax.com/ relevant to the attribute of the resource? Like in the above answer.

**Comment by emerkle826** [comment]
> Thanks @emerkle826 for the detailed answer. Can you please make sure the Terraform documentation pages contains the links to https://docs.datastax.com/ relevant to the attribute of the resource? Like in the above answer.

That is my plan. :+1:

**Comment by tringuyen-yw** [comment]
My I assume the Terraform documentation update would involve all the resources related to [DataStax Astra Provider](https://registry.terraform.io/providers/datastax/astra/latest/docs)

Because resources other than `astra_database` or `astra_role` mentioned in issues #79 and #80 also suffer from the incomplete documentation.

**Comment by emerkle826** [comment]
> My I assume the Terraform documentation update would involve all the resources related to [DataStax Astra Provider](https://registry.terraform.io/providers/datastax/astra/latest/docs)

Yes, I'll probably try to combine both of your issues into a single PR that revisits all the docs. I suspect most of the changes will simply add references to the existing Astra documentation, but not all. Some of this provider's variables aren't the exact same as what Astra documents, so for those, the docs will be more clear about what is allowed/expected/etc.

It will take me a bit of time to get around to all of it though.
