### ISSUE TITLE
TERRA-54 ⁃ Documentation: astra_role, what is the format of a DRN resource string and policy?

### ISSUE THREAD

**Issue by tringuyen-yw** [datastax/terraform-provider-astra#80]
### Terraform Version
Terraform v1.1.5
on linux_amd64

### Affected Resource(s)
- astra_role

The official Terraform doc: https://registry.terraform.io/providers/datastax/astra/latest/docs/resources/role gives a succint example of two attributes

```
resources   = ["drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73"]
  policy    = ["db-all-keyspace-create"]
```

The documentation needs more details on:

- Describe the format of a DRN resource string. Give a couple of example of the possible variations of resource string
- What are the valid values for `policy` ?

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-54) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-54
┆priority: Major

**Comment by emerkle826** [comment]
Same as #79, I will wait to close this once the docs have been updated, but to answer your questions:

> * Describe the format of a DRN resource string. Give a couple of example of the possible variations of resource string

The format is `"drn:astra:org:<organization UUID>"` where `organization UUID` is the UUID of the Astra organization you want to create your database in. The example in the docs doesn't really have any variation other than the UUID of the org. The `drn:astra:org:` part, for now, is required and doesn't have any other variations.

> * What are the valid values for `policy` ?

That list is rather long, but is documented here: https://docs.datastax.com/en/astra/docs/user-permissions.html#_operational_roles_detail . You may also find some more infor regarding custom roles here: https://docs.datastax.com/en/astra/docs/manage-custom-user-roles.html

**Comment by tringuyen-yw** [comment]
> The format is "drn:astra:org:<organization UUID>"

Could the DRN resource be more granular than that? For example, userA can only read a single table named `myKeyspace.myTable1`.

**Comment by emerkle826** [comment]
> Could the DRN resource be more granular than that? For example, userA can only read a single table named

You are correct. You can be more specific. Our tests actually has some other examples [here](https://github.com/datastax/terraform-provider-astra/blob/main/internal/provider/resource_role_test.go#L43-L51). Again, I'll update the docs to demonstrate this.
